### ISSUE TITLE
make lv2 fails because it cannot find String::empty

### ISSUE THREAD

**Issue by danielappelt** [DISTRHO/DISTRHO-Ports-Extra#1]
Somehow, I am not able to successfully make the LV2 plugins. "Building argotlunar2.lv2/argotlunar2" fails because String::empty is not defined. Is it possible that this plugin needs the following?:

```
#define JUCE_ALLOW_STATIC_NULL_VARIABLES 1
```

**Comment by falkTX** [comment]
This is a known issue. I haven't updated this repository to match the source yet.
Will do that at a later point.

**Comment by danielappelt** [comment]
I have created an [Arch User Repository package](https://aur.archlinux.org/packages/distrho-extra-lv2-git/) for the LV2 plugins now. As there is no complete distrho-ports package available in Arch, I decided to pull it in at build time in order to satisfy build dependencies. This is where I am applying the modification mentioned above for now.

**Comment by falkTX** [comment]
This is now fixed.
